name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flavioamanciodevops/seguranca_docker:${{ github.run_number }}

    - name: Docker Scout
      uses: docker/scout-action@v1.17.0
      with:
       command: quickview
       image: ${{ secrets.DOCKERHUB_USER }}/seguranca_docker:${{ github.run_number }}
       ignore-base: false
       dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
       dockerhub-password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Aqua Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKERHUB_USER }}/seguranca_docker:${{ github.run_number }}
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH,MEDIUM'